[package]
name = "enc"
version = "0.1.0"
authors = ["alesharikReserv@yandex.ru <alesharikReserv@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "decoder",
    "encoder"
]
