[package]
name = "encoder"
version = "0.1.0"
authors = ["alesharikReserv@yandex.ru <alesharikReserv@yandex.ru>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
lettre = "0.10.0-beta.3"
base64 = "0.13.0"
rand = { version = "0.8.3", features = ["getrandom"] }